### ISSUE TITLE
Feature Request: Rescale LoRA

### ISSUE THREAD

**Issue by AI-Casanova** [elias-gaeros/resize_lora#1]
I would like the option to rescale a LoRA prior to resizing.

Considering that you can compare the LoRA to a base model, this may also change the output size.

Thanks for the good work!

**Comment by elias-gaeros** [comment]
Good idea, I added it. You can now append `rescale=0.5` or whatever to the recipe.

> Considering that you can compare the LoRA to a base model, this may also change the output size.

It will offset the scores uniformly, but won't change which dims get selected.

**Comment by AI-Casanova** [comment]
> but won't change which dims get selected.

Rescaling to 0.2 with spn_ckpt resulted in a file size 1/10 the size. (as I guessed it might)

Also. can we get rescale in the file name so it doesn't overwrite?

**Comment by elias-gaeros** [comment]
> Rescaling to 0.2 with spn_ckpt resulted in a file size 1/10 the size. (as I guessed it might)

Yes if you use a fixed threshold. `rescale=0.2` will have the same effect than adding -log10(0.2) = 0.7 to the threshold.
eg. `spn_lora=1,thr=-1.4,rescale=0.2` ~ `spn_lora=1,thr=-0.7`

That is until I add a parameter for raising the singular values to a power. But this will wait until we have ways to plot statistics. There is already too many parameters for flying blind.

> Also. can we get rescale in the file name so it doesn't overwrite?

I added it.
